just_delete: false

delete_env: "{{ True if just_delete | bool == True else False }}"

delete_asg: false

delete_tg: false

delete_lb: false

delete_ec2: false

delete_lc: false

delete_sg: false

delete_key: false

delete_instances: false
