
ssh_local_path: files/keys
ssh_file: ec2_ssh_key
ssh_user: ec2_user

sg_name: lozano_poc
sg_desc: SG to be used on PoC by Matheus Lozano

# vpc_id: <DEFINE_IT>

# subnet_id: <DEFINE_IT>

delete_instances: false

# ami_id: <DEFINE_IT>

lc_name: lc_mlozano

aws_region: us-east-1

bootstrap_path: files/bootstrap

owner: mlozano

instance_type: t2.micro
instance_count: 1

volumes:
  device_name: "/dev/xvda"
  volume_type: "gp2"
  iops: 100
  # volume_snapshot: "<DEFINE_IT>"
  volume_size: 15
  delete_on_termination: yes

tg_name: tg-mlozano

lb_name: lb-mlozano
# lb_scheme: <DEFINE_IT>
azs:
  - "{{ aws_region + 'a' }}"
  - "{{ aws_region + 'b' }}"
  - "{{ aws_region + 'c' }}"
  - "{{ aws_region + 'd' }}"
  - "{{ aws_region + 'e' }}"
  - "{{ aws_region + 'f' }}"

asg_name: asg-mlozano