
aws_region: us-east-1

ssh_key: 
  local_path: "files/keys/"
  file: "ec2_ssh_key"
  user: "ec2_user"
  maldito: "files/keys/ec2_ssh_key.pub"

ssh_key_full_path: "{{ ssh_key['local_path'] + ssh_key['file'] + '.pub' }}"

security_group:
  name: lozano_poc
  description: SG to be used on PoC by Matheus Lozano

vpc:
  id: vpc-abcfc6d2

subnet:
  id: subnet-f1ffd1dd

ami:
  # id: ami-01e3b8c3a51e88954
  id: ami-02eac2c0129f6376b

bootstrap:
  path: "files/bootstrap/"
  countries: "bootstrap_countries.sh"

volumes:
  # device_name: "/dev/xvda"
  device_name: "/dev/sda1"
  volume_type: "gp2"
  iops: 100
  # volume_snapshot: "snap-042f3271b38c0f653"
  # volume_snapshot: "snap-010d360e3cba720ba"
  volume_size: 40
  delete_on_termination: yes

instance:
  type: t3.medium
  count: 1

launch_configuration:
  name: lc_mlozano

tags:
  owner: mlozano

target_group:
  name: tg-mlozano

load_balacer:
  name: lb-mlozano
  scheme: internet-facing

auto_scale_group:
  name: asg-mlozano

azs:
  - "{{ aws_region + 'a' }}"
  - "{{ aws_region + 'b' }}"
  - "{{ aws_region + 'c' }}"
  - "{{ aws_region + 'd' }}"
  - "{{ aws_region + 'e' }}"
  - "{{ aws_region + 'f' }}"
