
- name: Creating the load balancer
  ec2_elb_lb:
    state: present
    wait: yes
    purge_instance_ids: yes
    purge_listeners: yes
    purge_subnets: yes
    purge_zones: yes
    region: "{{ aws_region }}"
    name: "{{ load_balacer['name'] }}"
    scheme: "{{ load_balacer['scheme'] }}"
    security_group_ids: "{{ security_group_ids }}"
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 8000
    zones: "{{ azs }}"
  register: lb_return
