
- name: "Create launch configuration"
  ec2_lc:
    region: "{{ aws_region }}"
    name: "{{ launch_configuration['name'] }}"
    image_id: "{{ ami['id'] }}"
    key_name: "{{ ssh_key['file'] }}"
    security_groups: [ "{{ security_group['name'] }}" ]
    user_data: "{{ lookup('file', bootstrap['path'] + bootstrap['countries']) }}"
    instance_type: "{{ instance['type'] }}"
    instance_monitoring: yes
    volumes:
    - device_name: "{{ volumes['device_name'] }}"
      volume_type: "{{ volumes['volume_type'] }}"
      volume_size: "{{ volumes['volume_size'] }}"
      delete_on_termination: "{{ volumes['delete_on_termination'] }}"
  register: lc_return
