
- name: Deleting the Load Balancer
  ec2_elb_lb:
    state: absent
    wait: false
    region: "{{ aws_region }}"
    name: "{{ load_balacer['name'] }}"
  register: del_lb_return

- pause:
    seconds: 5
  when: del_lb_return is changed
