
- name: Waiting for dependencies be deleted
  pause:
    minutes: 2
  when: del_lc_return is changed

- name: "Delete Security Group"
  ec2_group:
    state: absent
    region: "{{ aws_region }}"
    name: "{{ item }}"
  with_items: "{{ security_group['name'] }}"
