
- name: Checking SSH key
  file:
    path: "{{ ssh_key['local_path'] }}/{{ item }}"
    state: file
  with_items:
    - "{{ ssh_key['file'] }}"
    - "{{ ssh_key['file'] }}.pub"
  register: file_exists
  ignore_errors: yes

- name: Generating the key
  shell: >-
    mkdir -p {{ ssh_key['local_path'] }}/
    && chmod 0600 {{ ssh_key['local_path'] }}/{{ ssh_key['file'] }}* || true
    && yes y | ssh-keygen -q -t rsa -f {{ ssh_key['local_path'] }}/{{ ssh_key['file'] }} -C "{{ ssh_key['user'] }}" -N ""
    && chmod 0400 {{ ssh_key['local_path'] }}/{{ ssh_key['file'] }}*
  register: ssh_key_created
  when: "'absent' in file_exists|json_query('results[*].state')"
