
- name: Deploying the ssh key {{ ssh_key['file'] }}
  ec2_key:
    name: "{{ ssh_key['file'] }}"
    region: "{{ aws_region }}"
    key_material: "{{ lookup('file', ssh_key['local_path'] + '/' + ssh_key['file'] + '.pub' )}}"
  when: ssh_key_created|changed
